kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: glance
  labels:
    system: openstack
    type: api
    component: glance
spec:
  replicas: {{ .Values.pod.replicas.api }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy }}
    {{ if eq .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_surge }}
    {{ end }}
  selector:
    matchLabels:
      name: glance
  template:
    metadata:
      labels:
        name: glance
{{ tuple . "glance" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
{{- if and (eq .Capabilities.KubeVersion.Major "1") (lt .Capabilities.KubeVersion.Minor "5") }}
        scheduler.alpha.kubernetes.io/affinity: >
            {{ tuple . "glance" "api" | include "kubernetes_pod_anti_affinity" }}
{{- end }}
    spec:
{{- if and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "7") }}
{{ tuple . "glance" "api" | include "kubernetes_pod_anti_affinity17" | indent 6 }}
{{- end }}
      containers:
        - name: glance-api
          securityContext:
            runAsUser: 0
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-glance-api:{{.Values.image_version_glance_api | default .Values.image_version | required "Please set glance.image_version or similar" }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.glance_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{.Values.global.glance_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "glance-api"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "glance-migration"
            - name: DEPENDENCY_SERVICE
              value: "postgres-glance,rabbitmq"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
            - name: PGAPPNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: api
              containerPort: {{.Values.global.glance_api_port_internal}}
          volumeMounts:
            - name: etcglance
              mountPath: /etc/glance
            - name: glance-etc
              mountPath: /etc/glance/glance-api.conf
              subPath: glance-api.conf
              readOnly: true
{{- if not .Values.swift_multi_tenant }}
            - name: glance-etc
              mountPath: /etc/glance/swift-store.conf
              subPath: swift-store.conf
              readOnly: true
{{- end }}
            - name: glance-etc
              mountPath: /etc/glance/policy.json
              subPath: policy.json
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/glance-api-paste.ini
              subPath: glance-api-paste.ini
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/logging.ini
              subPath: logging.ini
              readOnly: true
            - mountPath: /glance_store
              name: image-store
            - mountPath: /glance-patches
              name: glance-patches
        - name: glance-registry
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-glance-registry:{{.Values.image_version_glance_registry | default .Values.image_version | required "Please set glance.image_version or similar" }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 9191
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "glance-registry"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "glance"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
            - name: PGAPPNAME
              value: glance-registry
          ports:
            - name: registry
              containerPort: 9191
          volumeMounts:
            - name: etcglance
              mountPath: /etc/glance
            - name: glance-etc
              mountPath: /etc/glance/glance-registry.conf
              subPath: glance-registry.conf
              readOnly: true
{{- if not .Values.swift_multi_tenant }}
            - name: glance-etc
              mountPath: /etc/glance/swift-store.conf
              subPath: swift-store.conf
              readOnly: true
{{- end }}
            - name: glance-etc
              mountPath: /etc/glance/policy.json
              subPath: policy.json
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/glance-registry-paste.ini
              subPath: glance-registry-paste.ini
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/logging.ini
              subPath: logging.ini
              readOnly: true
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: etcglance
          emptyDir: {}
        - name: image-store
          persistentVolumeClaim:
            claimName: glance-pvclaim
        - name: glance-patches
          configMap:
            name: glance-patches
        - name: glance-etc
          configMap:
            name: glance-etc
