apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-etc
  labels:
    system: openstack
    type: configuration
    component: glance

data:
  glance-api.conf: |
{{ include (print .Template.BasePath "/etc/_glance-api.conf.tpl") . | indent 4 }}
  glance-registry.conf: |
{{ include (print .Template.BasePath "/etc/_glance-registry.conf.tpl") . | indent 4 }}
{{- if not .Values.swift_multi_tenant }}
  swift-store.conf: |
{{ include (print .Template.BasePath "/etc/_swift-store.conf.tpl") . | indent 4 }}
{{- end }}
  policy.json: |
{{ include (print .Template.BasePath "/etc/_glance-policy.json.tpl") . | indent 4 }}
  logging.ini: |
{{ include "loggerIni" .Values.logging | indent 4 }}
  glance-api-paste.ini: |
{{ include (print .Template.BasePath "/etc/_glance-api-paste.ini.tpl") . | indent 4 }}
  glance-registry-paste.ini: |
{{ include (print .Template.BasePath "/etc/_glance-registry-paste.ini.tpl") . | indent 4 }}
{{- if .Values.swift_multi_tenant }}
  maintain.sh: |
    set -xe
    glance-manage db sync
    psql -h postgres-{{ .Values.postgres.name }} -U {{ .Values.db_user }} {{ .Values.db_name }} -c "UPDATE image_locations AS l SET value='swift+https://objectstore-3.{{.Values.global.region}}.{{.Values.global.tld}}:443/v1/AUTH_' || i.owner || '/glance_' || i.id || '/' || i.id FROM images AS i WHERE i.id = l.image_id AND l.value LIKE 'swift+config://%'"
{{- end }}
