apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: glance
  labels:
    system: openstack
    type: api
    component: glance
  annotations:
     ingress.kubernetes.io/proxy-request-buffering: "off"
     ingress.kubernetes.io/proxy-body-size: "5g"
spec:
  tls:
    - secretName: tls-{{ include "glance_api_endpoint_host_public" . | replace "." "-" }}
      hosts: [{{include "glance_api_endpoint_host_public" .}}]
  rules:
    - host: {{include "glance_api_endpoint_host_public" .}}
      http:
        paths:
        - path: /
          backend:
            serviceName: glance
            servicePort: {{.Values.global.glance_api_port_internal}}
