apiVersion: batch/v1
kind: Job
metadata:
  name: glance-migration
  labels:
    system: openstack
    type: configuration
    component: glance
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: glance-migration
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-glance-api:{{.Values.image_version_glance_api | default .Values.image_version | required "Please set glance.image_version or similar" }}
          imagePullPolicy: IfNotPresent
          command:
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "glance-manage db_sync"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "postgres-glance"
          volumeMounts:
            - name: etcglance
              mountPath: /etc/glance
            - name: glance-etc
              mountPath: /etc/glance/glance.conf
              subPath: glance-api.conf
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/swift-store.conf
              subPath: swift-store.conf
              readOnly: true
            - name: glance-etc
              mountPath: /etc/glance/logging.ini
              subPath: logging.ini
              readOnly: true
      volumes:
        - name: etcglance
          emptyDir: {}
        - name: glance-etc
          configMap:
            name: glance-etc
