apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-console
  labels:
    system: openstack
    type: config
    component: ironic
data:
  default.conf: |
    server {
        listen       80;
        server_name  {{ include "ironic_console_endpoint_host_public" . }};

        location ~* "/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(.*)$" {
            proxy_pass http://unix:/shellinabox/$1.sock:/$2;
            proxy_set_header    Host      $host;
            proxy_http_version  1.1;
            proxy_redirect      off;
            proxy_buffering     off;
        }

        location /health {
            access_log off;
            return 204;
        }
    }
