apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-pxe
  labels:
    system: openstack
    type: config
    component: ironic
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /srv;
            autoindex   on;
            sendfile    on;
            tcp_nopush  on;
            tcp_nodelay on;
        }
    }
