apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: ironic-seed
spec:
  requires:
    - monsoon3/domain-default-seed
    - monsoon3/domain-monsoon3-seed

  roles:
    - cloud_compute_admin
    - cloud_network_admin

  services:
  - name: ironic
    type: baremetal
    description: Openstack baremetal provisioning service
 # uncomment once moved to helm-charts
 #    endpoints:
 #    - interface: admin
 #      region: {{ .Values.global.region }}
 #      url: https://{{ include "ironic_api_endpoint_host_public" .}}
 #    - interface: internal
 #      region: {{ .Values.global.region }}
 #      url: http://ironic-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:6385
 #    - interface: public
 #      region: {{ .Values.global.region }}
 #      url: http://ironic-api.{{ .Release.Namespace }}.svc.kubernetes.{{ .Values.global.region }}.{{ .Values.global.tld }}:6385

  flavors:
    - name: "zh1mlx1.large"
      id: "1000"
      vcpus: 120
      ram: 1048576
      disk: 837
      is_public: false
      description: HANA Baremetal 2 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
    - name: "zh2mlx1.xlarge"
      id: "1010"
      vcpus: 88
      ram: 2097152
      disk: 400
      is_public: false
      description: HANA Baremetal 4 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
    - name: "zh2mlx1.2xlarge"
      id: "1020"
      vcpus: 172
      ram: 4194304
      disk: 400
      is_public: false
      description: HANA Baremetal 8 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"
    - name: "zh2mlx1.3xlarge"
      id: "1030"
      vcpus: 172
      ram: 6291456
      disk: 400
      is_public: false
      description: HANA Baremetal 8 socket
      extra_specs:
        "capabilities:cpu_arch": "x86_64"

  domains:
  - name: Default
    users:
    - name: ironic
      description: Ironic Service
      #password: {{ .Values.global.ironic_service_password }}
      roles:
      - project: service
        role: service
      - project: service
        role: admin
      - project: service
        role: cloud_network_admin
      - project: service
        role: cloud_compute_admin

  - name: monsoon3
    description: "Converged Cloud Ironic base"
    projects:
    - name: ironic
      description: 'Ironic'
      flavors:
      - "1000"
      - "1010"
      - "1020"
      - "1030"