{{- if .Values.postgres.password }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-cinder
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sql: |
    CREATE DATABASE {{.Values.db_name}};
    CREATE ROLE {{.Values.db_user}} WITH ENCRYPTED PASSWORD '{{.Values.db_password}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.db_name}} TO {{.Values.db_user}};
{{- end }}
