{{- if .Values.nanny.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinder-nanny-bin
  namespace: monsoon3
  labels:
    system: openstack
    service: cinder-nanny
    component: cinder-nanny

data:
  cinder-nanny-start: |
{{ include (print $.Template.BasePath "/bin/_cinder-nanny-start.tpl") . | indent 4 }}
  cinder-db-purge: |
{{ include (print $.Template.BasePath "/bin/_cinder-db-purge.tpl") . | indent 4 }}
  cinder-quota-sync: |
{{ include (print $.Template.BasePath "/bin/_cinder-quota-sync.tpl") . | indent 4 }}
  db-cleanup-entries-without-valid-project: |
{{ include (print $.Template.BasePath "/bin/_db-cleanup-entries-without-valid-project.tpl") . | indent 4 }}
{{- end }}
