apiVersion: v1
kind: ConfigMap
metadata:
  name: designate-etc
  labels:
    system: openstack
    type: configuration
    component: designate

data:
  api-paste.ini: |
{{ include (print .Template.BasePath "/etc/_api-paste.ini.tpl") . | indent 4 }}
  designate.conf: |
{{ include (print .Template.BasePath "/etc/_designate.conf.tpl") . | indent 4 }}
  rndc.key: |
{{ include (print .Template.BasePath "/etc/_rndc.key.tpl") . | indent 4 }}
{{- if .Values.rndc_sap_internet_key }}
  rndc_sap_internet.key: |
{{ include (print .Template.BasePath "/etc/_rndc_sap_internet.key.tpl") . | indent 4 }}
{{- end }}
  pools.yaml: |
{{ include (print .Template.BasePath "/etc/_pools.yaml.tpl") . | indent 4 }}
  policy.json: |
{{ include (print .Template.BasePath "/etc/_designate-policy.json.tpl") . | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
