kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: nova-api
  labels:
    system: openstack
    type: api
    component: nova
spec:
  replicas: {{ if not .Values.pod.debug.api }}{{ .Values.pod.replicas.api }}{{ else }} 1 {{ end }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy }}
    {{ if eq .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_surge }}
    {{ end }}
  selector:
    matchLabels:
      name: nova-api
  template:
    metadata:
      labels:
        name: nova-api
{{ tuple . "nova" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
        configmap-bin-hash: {{ include (print $.Template.BasePath "/bin-configmap.yaml") . | sha256sum }}
{{- if and (eq .Capabilities.KubeVersion.Major "1") (lt .Capabilities.KubeVersion.Minor "5") }}
        scheduler.alpha.kubernetes.io/affinity: >
            {{ tuple . "nova" "api" | include "kubernetes_pod_anti_affinity" }}
{{- end }}
    spec:
{{- if .Values.pod.debug.api }}
      securityContext:
        runAsUser: 0
{{- end }}
      containers:
        - name: nova-api
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-api:{{.Values.image_version_nova_api}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "{{ if not .Values.pod.debug.api }}nova-api{{ else }}sleep inf{{ end }}"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_JOBS
              value: "nova-migration"
            - name: DEPENDENCY_SERVICE
              value: "postgres-nova,rabbitmq"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
{{- if .Values.python_warnings }}
            - name: PYTHONWARNINGS
              value: {{ .Values.python_warnings | quote }}
{{- end }}
{{- if not .Values.pod.debug.api }}
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.global.nova_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{.Values.global.nova_api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
{{- end }}
          ports:
            - name: nova-api
              containerPort: {{.Values.global.nova_api_port_internal}}
            - name: nova-metdata
              containerPort: {{.Values.global.nova_metadata_port_internal}}
          volumeMounts:
            - mountPath: /etc/nova
              name: etcnova
            - mountPath: /etc/nova/nova.conf
              name: nova-etc
              subPath: nova.conf
              readOnly: true
            - mountPath: /etc/nova/api-paste.ini
              name: nova-etc
              subPath: api-paste.ini
              readOnly: true
            - mountPath: /etc/nova/api_audit_map.conf
              name: nova-etc
              subPath: api_audit_map.conf
              readOnly: true
            - mountPath: /etc/nova/policy.json
              name: nova-etc
              subPath: policy.json
              readOnly: true
            - mountPath: /etc/nova/logging.conf
              name: nova-etc
              subPath: logging.conf
              readOnly: true
            - mountPath: /var/lib/kolla/venv/bin/iptables-restore
              name: nova-bin
              subPath: iptables-restore.mock
              readOnly: true
        - name: statsd
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: statsd
              containerPort: 9125
              protocol: UDP
            - name: metrics
              containerPort: {{.Values.port_metrics}}
      volumes:
        - name: etcnova
          emptyDir: {}
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: nova-bin
          configMap:
            name: nova-bin
            defaultMode: 0755

