kind: Service
apiVersion: v1

metadata:
  name: nova-console
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  selector:
    name: nova-console

  ports:
    - name: novnc
      port: {{.Values.global.nova_novnc_port_internal}}
      targetPort: {{.Values.global.nova_novnc_port_internal}}
    - name: spicehtml5
      port: {{.Values.global.nova_spicehtml5_port_internal}}
      targetPort: {{.Values.global.nova_spicehtml5_port_internal}}
    - name: serial
      port: {{.Values.global.nova_serial_port_internal}}
      targetPort: {{.Values.global.nova_serial_port_internal}}
    - name: shellinabox
      port: {{.Values.global.nova_shellinabox_port_internal}}
      targetPort: {{.Values.global.nova_shellinabox_port_internal}}
