apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-nova
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sql: |
    CREATE DATABASE {{.Values.db_name}};
    CREATE ROLE {{.Values.db_user}} WITH ENCRYPTED PASSWORD '{{.Values.db_password}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.db_name}} TO {{.Values.db_user}};

    CREATE DATABASE {{.Values.api_db_name}};
    CREATE ROLE {{.Values.api_db_user}} WITH ENCRYPTED PASSWORD '{{.Values.api_db_password}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.api_db_name}} TO {{.Values.api_db_user}};
