apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-etc
  labels:
    system: openstack
    type: configuration
    component: nova

data:
  nova.conf: |
{{ include (print .Template.BasePath "/etc/_nova.conf.tpl") . | indent 4 }}
  policy.json: |
{{ include (print .Template.BasePath "/etc/_nova-policy.json.tpl") . | indent 4 }}
  logging.conf: |
{{ include "loggerIni" .Values.logging | indent 4 }}
  api-paste.ini: |
{{ include (print .Template.BasePath "/etc/_api-paste.ini.tpl") . | indent 4 }}
  nova_audit_map.yaml: |
{{ include (print .Template.BasePath "/etc/_nova_audit_map.yaml.tpl") . | indent 4 }}
