{{- if .Values.nanny.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-nanny-bin
  namespace: monsoon3
  labels:
    system: openstack
    service: nova-nanny
    component: nova-nanny

data:
  nova-nanny-start: |
{{ include (print $.Template.BasePath "/bin/_nova-nanny-start.tpl") . | indent 4 }}
  nova-db-purge: |
{{ include (print $.Template.BasePath "/bin/_nova-db-purge.tpl") . | indent 4 }}
  nova-quota-sync: |
{{ include (print $.Template.BasePath "/bin/_nova-quota-sync.tpl") . | indent 4 }}
{{- end }}
