{{- if .Values.nanny.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nova-nanny
  namespace: monsoon3
  labels:
    system: openstack
    service: nova-nanny

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: nova-nanny
      annotations:
        checksum/openstack-nova-templates-nova-nanny-bin-configmap.yaml: {{ include (print $.Template.BasePath "/nanny-bin-configmap.yaml") . | sha256sum }}
        checksum/openstack-nova-templates-bin-nova-nanny-start.tpl: {{ include (print $.Template.BasePath "/bin/_nova-nanny-start.tpl") . | sha256sum }}
        checksum/openstack-nova-templates-bin-nova-db-purge.tpl: {{ include (print $.Template.BasePath "/bin/_nova-db-purge.tpl") . | sha256sum }}
        checksum/openstack-nova-templates-bin-nova-quota-sync.tpl: {{ include (print $.Template.BasePath "/bin/_nova-quota-sync.tpl") . | sha256sum }}
    spec:
      nodeSelector:
        zone: farm
      volumes:
        - name: nova-nanny-bin
          configMap:
            name: nova-nanny-bin
        - name: nova-etc
          configMap:
            name: nova-etc
      containers:
        - name: nova-nanny
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-api:{{.Values.image_version_nova_api}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "{{ if not .Values.pod.debug.nanny }}/bin/bash /nova-nanny-bin/nova-nanny-start{{ else }}sleep inf{{ end }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPENDENCY_SERVICE
              value: "postgres-nova,nova-api"
          volumeMounts:
            - mountPath: /nova-nanny-bin
              name: nova-nanny-bin
            - mountPath: /nova-etc
              name: nova-etc
{{- if .Values.db_cleanup.enabled }}
        - name: nova-cleanup
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/ubuntu-source-nova-api:{{.Values.image_version_nova_api}}
          imagePullPolicy: IfNotPresent
          command:
            - dumb-init
            - kubernetes-entrypoint
          env:
            - name: COMMAND
              value: "{{ if not .Values.pod.debug.nanny }}/usr/bin/python /nova-nanny-bin/db-cleanup-entries-without-valid-project --dry-run --iterations 14 --interval 720 --nova{{ else }}sleep inf{{ end }}"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEPENDENCY_SERVICE
              value: "postgres-nova,nova-api"
            - name: OS_AUTH_URL
              value: "https://{{ include "keystone_api_endpoint_host_public" . }}:443/v3"
            - name: OS_PROJECT_NAME
              value: "cloud_admin"
            - name: OS_PROJECT_DOMAIN_NAME
              value: "ccadmin"
            - name: OS_USERNAME
              value: "nova_nanny"
            - name: OS_USER_DOMAIN_NAME
              value: "Default"
            - name: OS_PASSWORD
              value: '{{ derivePassword 1 "long" .Values.global.master_password "nova_nanny" (include "keystone_api_endpoint_host_public" .) }}'
          volumeMounts:
            - mountPath: /nova-nanny-bin
              name: nova-nanny-bin
{{- end }}
{{- end }}
