{{- $opts := merge .Values.pgbouncer .Values.global.pgbouncer }}
{{- if $opts.enabled }}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{.Values.name}}-pgbouncer
  namespace:  {{.Release.Namespace}}
  labels:
    system: openstack
    component: {{.Values.name}}
spec:
  replicas: {{ .Values.pod.replicas.pgbouncer }}
  revisionHistoryLimit: {{ .Values.pod.lifecycle.upgrades.deployments.revision_history }}
  strategy:
    type: {{ .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy }}
    {{- if eq .Values.pod.lifecycle.upgrades.deployments.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.pod.lifecycle.upgrades.deployments.rolling_update.max_surge }}
    {{- end }}
  selector:
   matchLabels:
    name: {{.Values.name}}-pgbouncer
  template:
    metadata:
      labels:
        name: {{.Values.name}}-pgbouncer
{{ tuple . .Values.name "pgbouncer" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9200"
    spec:
{{ tuple . .Values.name "pgbouncer" | include "kubernetes_pod_anti_affinity17" | indent 6 }}
      terminationGracePeriodSeconds: 150
      containers:
        - name: pgbouncer
          image: {{.Values.global.image_repository}}/{{.Values.global.image_namespace}}/pgbouncer-k8s:{{$opts.image_version | default "latest" }}
          imagePullPolicy: IfNotPresent
{{- if $opts.debug }}
          command: ["sleep", "inf"]
{{- end }}
          env:
            - name: LABEL_SELECTOR
              value: "name=postgres-{{.Values.name}}"
            - name: LISTEN_PORT
              value: {{ $opts.config.listen_port | quote }}
            - name: LISTEN_BACKLOG
              value: {{ $opts.config.listen_backlog | quote }}
            - name: MAX_CLIENT_CONN
              value: {{ $opts.config.max_client_conn | quote }}
            - name: MIN_POOL_SIZE
              value: {{ $opts.config.min_pool_size | quote }}
            - name: DEFAULT_POOL_SIZE
              value: {{ $opts.config.default_pool_size | quote }}
            - name: RESERVE_POOL_SIZE
              value: {{ $opts.config.reserve_pool_size | quote }}
            - name: STATS_PASS
              value: {{ $opts.config.stats_pass | default (derivePassword 1 "long" "password" "stats_user" (print "postgres-" .Values.name "." .Release.Namespace ".svc.kubernetes." .Values.global.region "." .Values.global.tld)) | quote }}
{{- if not $opts.debug }}
          livenessProbe:
            exec:
              command:
              - pgbouncer-k8s-liveness
            initialDelaySeconds: 3
            periodSeconds: 1
            failureThreshold: 5
{{- end }}
          ports:
            - name: pgbouncer
              containerPort: {{ $opts.config.listen_port }}
{{- end }}
