{{- $opts := merge .Values.pgbouncer .Values.global.pgbouncer }}
{{- if $opts.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-pgbouncer
  namespace: {{ .Release.Namespace }}
  labels:
    system: openstack
    component: {{ .Values.name }}
data:
  {{- range $k, $v := $opts.config }}
  {{ quote $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
