apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-patches
  labels:
    system: openstack
    type: patches
    component: neutron

data:
  dhcp.diff: |
{{ .Files.Get "patches/dhcp.diff" | indent 4 }}
  ipam-backend-mixin.diff: |
{{ .Files.Get "patches/ipam_backend_mixin.diff" | indent 4 }}

