apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-etc-{{.Values.name}}
  labels:
    system: openstack
    type: configuration
    component: metrics

data:
  config.yml: |
    ---
    jobs:
    - name: "default"
      interval: '1m'
      connections:
      - "mysql://{{ .Values.db_user }}:{{ .Values.db_password }}@tcp({{ include (print $.Values.name "_db_host") . }}:3306)/{{ .Values.db_name }}"
      queries:
{{ toYaml .Values.customMetrics | indent 9}}
