dependencies:
  - name: utils
    repository: file://../utils
    version: 0.1.1
  - name: postgres
    repository: file://../postgres
    version: 0.1.0
  - name: pg_metrics
    repository: file://../pg_metrics
    version: 0.1.0
  - name: rabbitmq_notifications
    repository: file://../rabbitmq_notifications
    condition: openstack.nova.audit.enabled
    version: 0.0.1
