dependencies:
  - name: memcached
    repository: file://../memcached
    version: 0.1.0
  - name: rabbitmq
    repository: file://../rabbitmq
    version: 0.1.0
  - name: nova
    repository: file://../nova
    version: 0.1.1
    tags:
        - nova
  - name: cinder
    repository: file://../cinder
    version: 0.1.1
    tags:
        - cinder
  - name: healthchecks
    repository: file://../healthchecks
    version: 0.1.0
  - name: utils
    repository: file://../utils
    version: 0.1.1
