# Default values for openstack.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
tags:
  rabbitmq: true
  healthchecks: false

global:
  region: DEFINED-IN-REGION-CHART
  memcached_port_public: '11211'
  memcached_port_metrics: '9150'

  rabbitmq_default_user: openstack
  rabbitmq_admin_user: admin
  rabbitmq_metrics_user: monitoring
  rabbitmq_port_public: '5672'
  rabbitmq_port_management: '15672'
  rabbitmq_port_metrics: '9150'

  rabbitmq_default_pass: null
  rabbitmq_admin_pass: null
  rabbitmq_metrics_pass: null
  rabbit_transient_queues_ttl: 1800

  cfm_api_endpoint_protocol_public: https
  cfm_api_port_public: '443'
  cfm_service_password: null

  master_password: null

vcenter_operator:
  username:
  vcenter_exporter:
    enabled: DEFINED-IN-REGION-CHART
    image_version: DEFINED-IN-REGION-CHART
    listen_port: 9102
    interval: 120
    name_shortening_regex: DEFINED-IN-REGION-CHART
    docker_repo: DEFINED-IN-REGION-CHART
