apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-etc-{{.Values.name}}
  labels:
    system: openstack
    type: configuration
    component: database

data:
  my.cnf: |
{{ include (print .Template.BasePath "/etc/_my.cnf.tpl") . | indent 4 }}
