{{- if .Values.vcenter_operator.image_version }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: vcenter-operator
  namespace: {{ .Values.global.admin_namespace }}
data:
  namespace: monsoon3
  user_suffix: {{ .Values.global.user_suffix | default "" | quote }}
  password: {{ .Values.global.master_password | quote }}
{{- range $key, $value := .Values.vcenter_operator }}
  {{- $str := toJson $value }}
  {{ $key }}: {{if hasPrefix "\"" $str }}{{ $str }}{{ else }}{{ quote $str }}{{ end }}
{{- end }}
---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: vcenter-operator
  namespace: {{ .Values.global.admin_namespace }}
  labels:
    component: operator
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      name: vcenter-operator
  template:
    metadata:
      labels:
        name: vcenter-operator
      annotations:
        checksum/templates: {{ (.Files.Glob "vcenter-operator/*").AsConfig | sha256sum }}
    spec:
      restartPolicy: Always
      containers:
        - name: "vcenter-operator"
          command:
            - dumb-init
          args:
            - vcenter-operator
          env:
          - name: SERVICE_DOMAIN
            value: "cc.{{.Values.global.region}}.{{.Values.global.tld}}"
          image: "{{ .Values.global.image_repository}}/{{ .Values.global.image_namespace}}/ubuntu-source-vcenter-operator:{{ .Values.vcenter_operator.image_version}}"
          volumeMounts:
            - name: config
              mountPath: /var/lib/kolla/config_files
      volumes:
        - name: config
          configMap:
            name: vcenter-operator
{{- end }}
