# Default values for
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  glance_api_port_internal: REQUIRED
  image_namespace: REQUIRED
  image_repository: REQUIRED
  hypervisors: []
  osprofiler: {}
  pgbouncer:
    enabled: false

osprofiler: {}

pod:
  replicas:
    api: 2
  lifecycle:
    upgrades:
      deployments:
        revision_history: 5
        pod_replacement_strategy: RollingUpdate
        rolling_update:
           max_unavailable: 0
           max_surge: 1

image_version: null
image_version_glance_api: null
image_version_glance_registry: null

debug: "True"
db_name: glance
db_user: glance
db_password: null

port_metrics: '9102'
ops_middleware_enabled: false
sentry_dsn: DEFINE_IN_REGION_CHART

default_store: swift
swift_multi_tenant: true
# If not swift_multi_tenant, where to store the images
swift_domain:
swift_project:

pg_metrics:
  name: glance

postgres:
  name: glance
  users:
    glance: {}

logging:
    formatters:
        context:
            class: oslo_log.formatters.ContextFormatter
        default:
            format: "%(message)s"
    handlers:
        stdout:
            class: StreamHandler
            args: "(sys.stdout,)"
            formatter: context
        "null":
            class: logging.NullHandler
            args: "()"
            formatter: default
        sentry:
            class: raven.handlers.logging.SentryHandler
            level: ERROR
            args: "()"
    loggers:
        root:
            handlers: "null"
            level: WARNING
        glance:
            handlers: stdout, sentry
            level: DEBUG
        glance_store:
            handlers: stdout, sentry
            level: DEBUG
        amqp:
            handlers: stdout, sentry
            level: WARNING
        amqplib:
            handlers: stdout, sentry
            level: WARNING
        boto:
            handlers: stdout, sentry
            level: WARNING
        eventlet.wsgi.server:
            handlers: stdout, sentry
            level: INFO
        sqlalchemy:
            handlers: stdout, sentry
            level: WARNING
        suds:
            handlers: stdout, sentry
            level: WARNING
