# Default values for global.postgres_
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  image_namespace: REQUIRED
  image_repository: REQUIRED
  pgbouncer:
    enabled: false
    image_version: null
    config:
      stats_users: "stats_user"
      admin_users: "admin_user"
      autodb_idle_timeout: 3600
      max_client_conn: 16384
      reserve_pool_size: 4
      min_pool_size: 1
      default_pool_size: 4
      server_check_delay: 30
      unix_socket_dir: "/tmp"
      listen_addr: "0.0.0.0"
      listen_port: 6543
      listen_backlog: 256
      auth_type: "md5"
      tcp_keepalive: 1
      tcp_keepcnt: 10
      tcp_keepidle: 5
      tcp_keepintvl: 5
      ignore_startup_parameters: "extra_float_digits"
      log_connections: 0
      log_disconnections: 0
      pool_mode: "transaction"
      application_name_add_host: 1

name: null
user: postgres
password: null
port_public: '5432'
port_private: '5432'
hba_cidr: 0.0.0.0/0
auth_method: password

users: {}
scripts: {}

image_version_postgres: '9.4.14'

pod:
  replicas:
    pgbouncer: 3
  lifecycle:
    upgrades:
      deployments:
        revision_history: 5
        pod_replacement_strategy: "RollingUpdate"
        rolling_update:
          max_unavailable: 1
          max_surge: 1

persistence:
  enabled: true

backup:
  enabled: false
  metrics: false
  interval_full: 1 hours
#  interval_incr: NOT-USED-CURRENT
  image_version: v0.5.14
  os_password: DEFINED-IN-REGION-SECRETS
  os_username: db_backup
  os_user_domain: Default
  os_project_name: master
  os_project_domain: ccadmin

pgbouncer:
  config: {}
